apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: test
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: eric.calabretta@harness.io
  lifecycle: experimental
